# Generated by Django 2.2.5 on 2019-09-27 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='article',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
