# Generated by Django 2.2.5 on 2019-09-27 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_news_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='cover',
            field=models.TextField(blank=True),
        ),
    ]
