# Generated by Django 2.2.5 on 2019-09-28 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190928_1042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='article_id',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='likes_count',
        ),
        migrations.AddField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.News'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='date',
            field=models.DateField(default='2019-09-28'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='intro',
            field=models.TextField(default='Произошла смертб'),
            preserve_default=False,
        ),
    ]
