# Generated by Django 2.2.5 on 2019-09-28 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190928_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='tags',
        ),
        migrations.AlterField(
            model_name='news',
            name='authorPosition',
            field=models.FloatField(default=5),
        ),
        migrations.AlterField(
            model_name='news',
            name='concrete',
            field=models.FloatField(default=1),
        ),
    ]
